### ISSUE TITLE
Cookies for Myntra is not working 

### ISSUE THREAD

**Issue by heykush** [shibisuriya/Amazon-Web-Scraper#3]
Could you please check and update the headers, or check for cookies?

Is there any method which cookies never expire or increase the expiring time?

**Comment by shibisuriya** [comment]
I don't understand, you have to manually copy and paste cookie for this to work....

**Comment by shibisuriya** [comment]
You don't even have to be logged in for this to work...

**Comment by heykush** [comment]
agree, but cookies are expiring after 2-3 hours every time, is there any method available for using client id or something?

**Comment by shibisuriya** [comment]
2-3 hours? What why do you keep the script running for 2-3 hours? What are trying to do?

**Comment by heykush** [comment]
is there any place where we can connect and talk about this in detail, please?

**Comment by shibisuriya** [comment]
We talk in discord? Or here itself.

**Comment by heykush** [comment]
discord username?

**Comment by shibisuriya** [comment]
shibi#6781

**Comment by heykush** [comment]
request sent please check

**Comment by shibisuriya** [comment]
Updated, cookie.

**Comment by heykush** [comment]
Cookies were again dead, please reply on discord. Thank you
